sudo: false
language: python
python:
    - "3.5"
install: pip install -r requirements.txt
script:
   - git clone https://github.com/regardscitoyens/the-law-factory-parser-test-cases.git tests_cases
   - python tests/test_steps.py
   - python tests/test_regressions.py tests_cases
notifications:
  irc: 
    channels:
      - "chat.freenode.net#regardscitoyens"
    template:
      - "%{repository_slug} - %{commit_subject} : %{message}"
    on_success: never
    on_failure: change
    skip_join: true
